Repository BaSP-a2022/marta-b-trackgenix-app, pull requests merged in 2022-11, with the labels that each got.

#6 BaSP-TG-10: Add and Edit Tasks
  src/Components/Tasks/DeleteButton/delete-button.module.css
  src/Components/Tasks/ModalDelete/modal-delete.module.css
  src/Components/Tasks/ModalDelete/modalDelete.jsx
  src/Components/Tasks/Row/row.jsx
  src/Components/Tasks/Row/row.module.css
  src/Components/Tasks/form.jsx
  src/Components/Tasks/tasks.module.css
Labels: Ready for Deploy

#8 BaSP-TG-2-B: Super Admin - Add and Edit
  package-lock.json
  src/Components/Layout/index.js
  src/Components/SuperAdmins/Button/Button.jsx
  src/Components/SuperAdmins/Button/button.module.css
  src/Components/SuperAdmins/Form/Form.jsx
  src/Components/SuperAdmins/Form/form.module.css
  src/Components/SuperAdmins/List/List.jsx
  src/Components/SuperAdmins/List/list.module.css
  src/Components/SuperAdmins/ListItem/ListItem.jsx
  src/Components/SuperAdmins/ListItem/listItem.module.css
  src/Components/SuperAdmins/Modal/Modal.jsx
  src/Components/SuperAdmins/Modal/modal.module.css
  src/Components/SuperAdmins/index.js
  src/Components/SuperAdmins/super-admins.module.css
Labels: Ready for Deploy

#2 BaSP-TG-2: Super Admin - List and Delete
  src/Components/Layout/index.js
  src/Components/Tasks/DeleteButton/delete-button.module.css
  src/Components/Tasks/DeleteButton/deleteButton.jsx
  src/Components/Tasks/ModalDelete/modal-delete.module.css
  src/Components/Tasks/ModalDelete/modalDelete.jsx
  src/Components/Tasks/Row/row.jsx
  src/Components/Tasks/Row/row.module.css
  src/Components/Tasks/Table/table.jsx
  src/Components/Tasks/Table/table.module.css
  src/Components/Tasks/form.jsx
  src/Components/Tasks/index.js
  src/Components/Tasks/index.jsx
  src/Components/Tasks/tasks.module.css
Labels: Ready for QA

#4 BaSP-TG-4: Projects Page - List and Delete
  src/Components/Layout/index.js
  src/Components/Projects/index.js
  src/Components/Projects/index.jsx
  src/Components/Projects/modal.jsx
  src/Components/Projects/modal.module.css
  src/Components/Projects/projectForm.jsx
  src/Components/Projects/projectForm.module.css
  src/Components/Projects/projects.module.css
Labels: Ready for Deploy

#5 BaSP-TG-9-A: Admin - List and Delete
  package-lock.json
  src/Components/Admins/admins.module.css
  src/Components/Admins/deleteButton.jsx
  src/Components/Admins/index.js
  src/Components/Admins/modal-delete.module.css
  src/Components/Admins/modalDelete.jsx
  src/Components/Admins/row.jsx
  src/Components/Admins/table.jsx
  src/Components/Admins/table.module.css
Labels: Ready for Deploy

#7 BaSP-TG-9-B: Admin - Add and Edit
  src/Components/Admins/admins.module.css
  src/Components/Admins/form.jsx
  src/Components/Admins/form.module.css
  src/Components/Admins/row.jsx
  src/Components/Admins/table.jsx
  src/Components/Layout/index.js
Labels: Ready for Deploy

#3 BaSP-TG-05: list and delete employees
  README.md
  package-lock.json
  package.json
  src/Components/Employees/Icon-add-employee.png
  src/Components/Employees/Icon-awesome-trash.png
  src/Components/Employees/Icon-edit-employee.png
  src/Components/Employees/Modal/index.js
  src/Components/Employees/Modal/modal.module.css
  src/Components/Employees/employees.module.css
  src/Components/Employees/index.js
  src/Components/Footer/footer.module.css
  src/Components/Header/header.module.css
  src/Components/Home/home.module.css
  src/Components/Projects/projects.module.css
  src/Components/SuperAdmins/super-admins.module.css
  src/Components/Tasks/form.jsx
  src/Components/Tasks/tasks.module.css
  src/Components/TimeSheets/time-sheets.module.css
  src/index.css
Labels: Ready for QA

#9 BaSP-TG-07: add and edit employee
  package.json
  src/Components/Employees/AddEmployee/index.js
  src/Components/Employees/Modal/index.js
  src/Components/Employees/employees.module.css
  src/Components/Employees/index.js
  src/Components/Layout/index.js
  src/Components/Tasks/form.jsx
  src/Components/Tasks/tasks.module.css
Labels: Ready for Deploy

#11 BaSP-TG-28: Set up React Router
  package-lock.json
  package.json
  src/Components/Layout/index.js
Labels: Ready for Deploy

#12 BaSP-TG-30: Button component
  src/Components/Shared/Button/button.module.css
  src/Components/Shared/Button/index.jsx
Labels: Ready for QA

#13 BaSP-TG-29: Create Modal component
  src/Components/Shared/Button/button.module.css
  src/Components/Shared/Button/index.jsx
  src/Components/Shared/Modal/Modal.jsx
  src/Components/Shared/Modal/modal.module.css
Labels: Ready for Deploy

#15 BaSP-TG-33: Header, sidebar and Footer components
  public/assets/images/facebook.svg
  public/assets/images/github.svg
  public/assets/images/hamb-menu.svg
  public/assets/images/home.svg
  public/assets/images/instagram-negative.svg
  public/assets/images/instagram.svg
  public/assets/images/linkedIn.svg
  public/assets/images/list.svg
  public/assets/images/logout.svg
  public/assets/images/radium.png
  public/assets/images/twitter.svg
  src/Components/Admins/admins.module.css
  src/Components/Footer/footer.module.css
  src/Components/Footer/index.js
  src/Components/Header/header.module.css
  src/Components/Header/index.js
  src/Components/Layout/index.js
  src/Components/Layout/layout.module.css
  src/Components/Sidebar/index.js
  src/Components/Sidebar/sidebar.module.css
  src/index.css
Labels: help wanted

#16 BaSP-TG-47: update app Readme file
  README.md
Labels: Ready for Deploy

#14 BaSP-TG-32: Create Table Component
  src/Components/Shared/Table/index.jsx
  src/Components/Shared/Table/table.module.css
Labels: Ready for Deploy

#17 BaSP-TG-31: create row component and styles
  src/Components/Shared/Row/index.jsx
  src/Components/Shared/Row/row.module.css
Labels: Ready for Deploy

#19 BaSP-TG-39: Implement Shared Components in Project component
  src/Components/Layout/index.js
  src/Components/Projects/index.jsx
  src/Components/Projects/modal.jsx
  src/Components/Projects/modal.module.css
  src/Components/Projects/projectForm.jsx
  src/Components/Projects/projectForm.module.css
  src/Components/Projects/projects.module.css
  src/Components/Shared/Row/index.jsx
Labels: Ready for Deploy

#21 BaSP-TG-38: Tasks add shared components
  src/Components/Layout/index.js
  src/Components/Shared/Row/index.jsx
  src/Components/Tasks/DeleteButton/delete-button.module.css
  src/Components/Tasks/DeleteButton/deleteButton.jsx
  src/Components/Tasks/ModalDelete/modal-delete.module.css
  src/Components/Tasks/ModalDelete/modalDelete.jsx
  src/Components/Tasks/Row/row.jsx
  src/Components/Tasks/Row/row.module.css
  src/Components/Tasks/Table/table.jsx
  src/Components/Tasks/Table/table.module.css
  src/Components/Tasks/form.jsx
  src/Components/Tasks/index.jsx
Labels: Ready for Review

#22 BaSP-TG-34: Employee, added shared components
  src/Components/Employees/AddEmployee/index.js
  src/Components/Employees/Form/form.module.css
  src/Components/Employees/Form/index.js
  src/Components/Employees/Icon-add-employee.png
  src/Components/Employees/Icon-awesome-trash.png
  src/Components/Employees/Icon-edit-employee.png
  src/Components/Employees/Modal/index.js
  src/Components/Employees/Modal/modal.module.css
  src/Components/Employees/employees.module.css
  src/Components/Employees/index.js
  src/Components/Layout/index.js
  src/Components/Sidebar/index.js
  src/Components/Sidebar/sidebar.module.css
Labels: Ready for Deploy

#18 BaSP-TG-35: admins add shared components
  src/Components/Admins/admins.module.css
  src/Components/Admins/deleteButton.jsx
  src/Components/Admins/form.jsx
  src/Components/Admins/index.js
  src/Components/Admins/modal-delete.module.css
  src/Components/Admins/modalDelete.jsx
  src/Components/Admins/row.jsx
  src/Components/Admins/table.jsx
  src/Components/Admins/table.module.css
  src/Components/Employees/AddEmployee/employeesForm.module.css
  src/Components/Employees/AddEmployee/index.js
  src/Components/Layout/index.js
  src/Components/Projects/projectForm.jsx
  src/Components/Shared/Row/index.jsx
  src/Components/Shared/Table/index.jsx
Labels: Ready for Deploy

#23 BaSP-TG-54: Setup Redux
  package-lock.json
  package.json
  src/index.js
  src/redux/admins/actions.js
  src/redux/admins/constants.js
  src/redux/admins/reducer.js
  src/redux/admins/thunks.js
  src/redux/employees/actions.js
  src/redux/employees/constants.js
  src/redux/employees/reducer.js
  src/redux/employees/thunks.js
  src/redux/projects/actions.js
  src/redux/projects/constants.js
  src/redux/projects/reducer.js
  src/redux/projects/thunks.js
  src/redux/rootReducer.js
  src/redux/store.js
  src/redux/super-admins/actions.js
  src/redux/super-admins/constants.js
  src/redux/super-admins/reducer.js
  src/redux/super-admins/thunks.js
  src/redux/tasks/actions.js
  src/redux/tasks/constants.js
  src/redux/tasks/reducer.js
  src/redux/tasks/thunks.js
  src/redux/timesheets/actions.js
  src/redux/timesheets/constants.js
  src/redux/timesheets/reducer.js
  src/redux/timesheets/thunks.js
Labels: Ready for Deploy

#26 BaSP-TG-62: Projects Redux - GET
  src/Components/Projects/index.jsx
  src/redux/projects/actions.js
  src/redux/projects/constants.js
  src/redux/projects/reducer.js
  src/redux/projects/thunks.js
Labels: Ready for Deploy

#25 BaSP-TG-67: Spinner shared component
  src/Components/Shared/Spinner/index.jsx
  src/Components/Shared/Spinner/spinner.module.css
Labels: Ready for Deploy

#28 BaSP-TG-64: tasks redux get
  src/Components/Tasks/index.jsx
  src/redux/tasks/actions.js
  src/redux/tasks/constants.js
  src/redux/tasks/reducer.js
  src/redux/tasks/thunks.js
Labels: Ready for Deploy

#27 BaSP-TG-60: get employees with redux
  src/Components/Employees/index.js
  src/redux/employees/actions.js
  src/redux/employees/constants.js
  src/redux/employees/reducer.js
  src/redux/employees/thunks.js
Labels: Ready for Deploy

#29 BaSP-TG-57: admins GET projects/employees with redux
  src/Components/Admins/index.js
Labels: Ready for Review

#30 BaSP-TG-56: Super admins redux create, update and delete
  src/Components/SuperAdmins/Form/Form.jsx
  src/Components/SuperAdmins/index.js
  src/redux/super-admins/actions.js
  src/redux/super-admins/constants.js
  src/redux/super-admins/reducer.js
  src/redux/super-admins/thunks.js
Labels: Ready for Deploy

#31 BaSP-TG-61 : employees create, update & delete with redux
  src/Components/Employees/Form/index.js
  src/Components/Employees/employees.module.css
  src/Components/Employees/index.js
  src/Components/Employees/index.jsx
  src/redux/employees/actions.js
  src/redux/employees/constants.js
  src/redux/employees/reducer.js
  src/redux/employees/thunks.js
Labels: Ready for Deploy

#33 BaSP-TG-63: Projects Redux - CREATE, DELETE, PUT and GET BY ID
  src/Components/Projects/index.jsx
  src/Components/Projects/projectForm.jsx
  src/redux/projects/actions.js
  src/redux/projects/constants.js
  src/redux/projects/reducer.js
  src/redux/projects/thunks.js
Labels: Ready for Deploy

#34 BaSP-TG-74: Input Component
  src/Components/Shared/Input/index.jsx
  src/Components/Shared/Input/input.module.css
Labels: Ready for Deploy

#35 BaSP-TG-59: create, delete and edit employees and projects from admins
  src/Components/Admins/index.js
  src/Components/Admins/index.jsx
  src/Components/Employees/Form/index.js
  src/Components/Layout/index.js
Labels: Ready for Deploy

#37 BaSP-TG-85: Select Component
  src/Components/Shared/Select/index.jsx
  src/Components/Shared/Select/select.module.css
Labels: Ready for Deploy

#36 BaSP-TG-86: Hotfix - Show Projects & Show Employees buttons on Projects and Employees pages
  src/Components/Employees/index.jsx
  src/Components/Shared/Modal/modal.module.css
  src/Components/Shared/Row/index.jsx
Labels: Ready for Deploy

#38 BaSP-TG-08: Create TimeSheet component, add Shared Components and apply Redux
  src/Components/Layout/index.js
  src/Components/Shared/Row/index.jsx
  src/Components/TimeSheets/Form/form.module.css
  src/Components/TimeSheets/Form/index.jsx
  src/Components/TimeSheets/index.js
  src/Components/TimeSheets/index.jsx
  src/Components/TimeSheets/time-sheets.module.css
  src/redux/timesheets/actions.js
  src/redux/timesheets/constants.js
  src/redux/timesheets/reducer.js
  src/redux/timesheets/thunks.js
Labels: Ready for Deploy

#39 BaSP-TG-70: Setup libraries, absolute routes and lazy loading
  jsconfig.json
  package-lock.json
  package.json
  src/Components/Employees/index.jsx
  src/Components/Layout/index.js
  src/Components/Shared/index.js
  src/Routes/admin.js
  src/Routes/employee.js
  src/Routes/index.js
  src/Routes/project.js
  src/Routes/super-admin.js
  src/Routes/task.js
  src/Routes/timesheet.js
  src/index.js
Labels: Ready for Deploy

#41 BaSP-TG-89: Hotfix: Routes, Thunk in employee, and Select Component
  src/Components/Shared/Select/index.jsx
  src/Routes/admin.js
  src/redux/employees/thunks.js
Labels: Ready for Deploy

#40 BaSP-TG-80: Form tasks
  src/Components/Tasks/Form/index.jsx
  src/Components/Tasks/Form/validations.jsx
  src/Components/Tasks/index.jsx
  src/Components/Tasks/tasks.module.css
  src/Routes/task.js
Labels: Ready for Deploy

#44 BaSP-TG-76: Super Admin Form
  src/Components/SuperAdmins/Form/Form.jsx
  src/Components/SuperAdmins/Form/form.module.css
  src/Components/SuperAdmins/Form/index.jsx
  src/Components/SuperAdmins/Form/validations.jsx
  src/Components/SuperAdmins/index.js
  src/Routes/super-admin.js
Labels: Ready for Deploy

#43 BaSP-TG-79: Form timesheets
  src/Components/TimeSheets/Form/form.module.css
  src/Components/TimeSheets/Form/index.jsx
  src/Components/TimeSheets/Form/validations.jsx
  src/Components/TimeSheets/index.jsx
  src/redux/timesheets/reducer.js
Labels: Ready for Deploy

#45 BaSP-TG-78: Projects Form & Validations
  src/Components/Projects/Form/index.jsx
  src/Components/Projects/Form/projectForm.module.css
  src/Components/Projects/Form/validations.jsx
  src/Components/Projects/index.jsx
  src/Components/Projects/projectForm.jsx
  src/Routes/admin.js
  src/Routes/project.js
Labels: Ready for Deploy

#42 BaSP-TG-77: Form employee with react hook form
  src/Components/Employees/Form/index.js
  src/Components/Employees/Form/index.jsx
  src/Components/Employees/Form/validations.jsx
Labels: Ready for QA

#46 BaSP-TG-72: employee layout
  src/Components/Employees/AddEmployee/employeesForm.module.css
  src/Components/Employees/AddEmployee/index.js
  src/Components/Employees/Home/home.module.css
  src/Components/Employees/Home/index.jsx
  src/Components/Employees/Profile/index.jsx
  src/Components/Employees/Profile/profile.module.css
  src/Components/Employees/Profile/validations.jsx
  src/Components/Employees/Sidebar/index.jsx
  src/Components/Employees/Sidebar/sidebar.module.css
  src/Components/Employees/Timesheets/AddTimesheet/index.jsx
  src/Components/Employees/Timesheets/AddTimesheet/validations.jsx
  src/Components/Employees/Timesheets/index.jsx
  src/Components/Employees/Timesheets/timeSheets.module.css
  src/Components/Header/header.module.css
  src/Components/Home/index.js
  src/Components/Layout/layout.module.css
  src/Components/Sidebar/index.js
  src/Components/Sidebar/sidebar.module.css
  src/Routes/employee.js
  src/Routes/index.js
Labels: Ready for Deploy

#47 BaSP-TG-91: Change button, sidebar and table styles
  public/assets/images/facebook.svg
  public/assets/images/github.svg
  public/assets/images/instagram-negative.svg
  public/assets/images/instagram.svg
  public/assets/images/linkedIn.svg
  public/assets/images/twitter.svg
  src/Components/Admins/index.jsx
  src/Components/Layout/layout.module.css
  src/Components/Shared/Table/index.jsx
  src/Components/Shared/Table/table.module.css
  src/Components/Sidebar/sidebar.module.css
Labels: Ready for Deploy

#49 BaSP-TG-92: Set Up Firebase
  package-lock.json
  package.json
  src/Components/Auth/Login/index.jsx
  src/Components/Auth/SignUp/index.jsx
  src/Components/Employees/Sidebar/index.jsx
  src/Components/Employees/Sidebar/sidebar.module.css
  src/Components/Footer/index.js
  src/Components/Header/header.module.css
  src/Components/Home/index.js
  src/Components/Layout/index.js
  src/Components/Sidebar/index.js
  src/Components/Sidebar/sidebar.module.css
  src/Routes/admin.js
  src/Routes/auth.js
  src/Routes/employee.js
  src/Routes/index.js
  src/Routes/privateRoute.js
  src/Routes/project.js
  src/Routes/super-admin.js
  src/Routes/task.js
  src/Routes/timesheet.js
  src/helpers/firebase/index.js
  src/index.js
  src/redux/auth/actions.js
  src/redux/auth/constants.js
  src/redux/auth/reducer.js
  src/redux/auth/thunks.js
  src/redux/rootReducer.js
Labels: Ready for Deploy
