Repository BaSP-a2022/marta-b-trackgenix-app, pull requests merged in 2022-12, with the labels that each got.

#52 BaSP-TG-97: login firebase functionality in FE
  src/Components/Auth/Login/index.jsx
  src/Components/Auth/Login/login.module.css
  src/Components/Auth/Login/validations.js
  src/Components/Auth/SignUp/index.jsx
  src/Components/Employees/Form/index.jsx
  src/Components/Employees/Form/validations.jsx
  src/Components/Employees/Home/index.jsx
  src/Components/Employees/Profile/index.jsx
  src/Components/Employees/Projects/index.jsx
  src/Components/Employees/Projects/projects.module.css
  src/Components/Employees/Timesheets/AddTimesheet/index.jsx
  src/Components/Employees/Timesheets/index.jsx
  src/Components/Employees/index.jsx
  src/Components/Home/index.js
  src/Components/Projects/index.jsx
  src/Components/Sidebar/index.js
  src/Components/SuperAdmins/Form/validations.jsx
  src/Components/SuperAdmins/index.js
  src/Components/Tasks/index.jsx
  src/Components/TimeSheets/index.jsx
  src/Routes/admin.js
  src/Routes/auth.js
  src/Routes/employee.js
  src/Routes/employees.js
  src/Routes/index.js
  src/Routes/privateRoute.js
  src/Routes/super-admin.js
  src/helpers/firebase/index.js
  src/redux/auth/actions.js
  src/redux/auth/constants.js
  src/redux/auth/reducer.js
  src/redux/auth/thunks.js
  src/redux/employees/thunks.js
  src/redux/projects/thunks.js
  src/redux/super-admins/thunks.js
  src/redux/tasks/thunks.js
  src/redux/timesheets/thunks.js
Labels: Ready for Deploy

#54 BaSP-TG-44: Assign Employee feature
  src/Components/Projects/index.jsx
  src/Components/Projects/validations.jsx
  src/Components/Shared/Row/index.jsx
  src/Components/Shared/Table/index.jsx
  src/Routes/admin.js
  src/Routes/project.js
  src/redux/projects/actions.js
  src/redux/projects/constants.js
  src/redux/projects/reducer.js
  src/redux/projects/thunks.js
Labels: Ready for Deploy

#55 BaSP-TG-111: Modify admins features and rights
  src/Components/Employees/index.jsx
  src/Routes/admin.js
Labels: Ready for Deploy

#56 BaSP-TG-108: Add PM feature
  src/Components/Employees/Projects/index.jsx
  src/Components/Projects/index.jsx
  src/Components/Projects/validations.jsx
  src/Components/Shared/Row/index.jsx
  src/Components/Tasks/index.jsx
  src/Routes/employee.js
Labels: Ready for Deploy

#57 BaSP-TG-120: hotfix - problem with employees modal in projects
  src/Components/Shared/Row/index.jsx
Labels: Ready for Review

#58 BaSP-TG-110: Fix table and sidebar styles
  src/Components/Employees/index.jsx
  src/Components/Header/header.module.css
  src/Components/Header/index.js
  src/Components/Layout/layout.module.css
  src/Components/Shared/Button/button.module.css
  src/Components/Shared/Input/input.module.css
  src/Components/Shared/Modal/Modal.jsx
  src/Components/Shared/Modal/modal.module.css
  src/Components/Shared/Table/index.jsx
  src/Components/Shared/Table/table.module.css
  src/Components/Sidebar/index.js
  src/Components/Sidebar/sidebar.module.css
  src/index.css
Labels: Ready for Deploy

#60 BaSP-TG-123: Install font awesome library for react
  package-lock.json
  package.json
  public/assets/images/facebook.svg
  public/assets/images/github.svg
  public/assets/images/hamb-menu.svg
  public/assets/images/home.svg
  public/assets/images/instagram.svg
  public/assets/images/linkedIn.svg
  public/assets/images/list.svg
  public/assets/images/logout.svg
  public/assets/images/twitter.svg
  src/Components/Employees/Timesheets/index.jsx
  src/Components/Employees/Timesheets/timeSheets.module.css
  src/Components/Footer/footer.module.css
  src/Components/Footer/index.js
  src/Components/Projects/index.jsx
  src/Components/Projects/projects.module.css
  src/Components/Shared/Row/index.jsx
  src/Components/Shared/Row/row.module.css
  src/Components/Sidebar/index.js
  src/Components/Sidebar/sidebar.module.css
  src/Components/SuperAdmins/index.js
  src/Components/SuperAdmins/super-admins.module.css
  src/Components/Tasks/index.jsx
  src/Components/Tasks/tasks.module.css
  src/Components/TimeSheets/index.jsx
  src/Components/TimeSheets/time-sheets.module.css
Labels: Ready for Deploy

#59 BaSP-TG-119: Hotfix - Reload Issue
  src/Components/Auth/Login/index.jsx
  src/Components/Employees/Home/index.jsx
  src/Components/Employees/Profile/index.jsx
  src/Components/Shared/Row/index.jsx
  src/Routes/employee.js
  src/Routes/index.js
  src/Routes/privateRoute.js
  src/helpers/firebase/index.js
  src/redux/auth/actions.js
  src/redux/auth/reducer.js
  src/redux/auth/thunks.js
Labels: Ready for Deploy

#61 BaSP-TG-126: fix styles and add icons
  src/Components/Auth/Login/index.jsx
  src/Components/Auth/Login/login.module.css
  src/Components/Projects/index.jsx
  src/Components/Shared/Row/index.jsx
  src/Components/Shared/Row/row.module.css
  src/Components/Sidebar/index.js
  src/Components/Sidebar/sidebar.module.css
Labels: Ready for Deploy

#62 TG-135: Set login as default page
  src/Components/Employees/Home/home.module.css
  src/Components/Employees/Home/index.jsx
  src/Components/Home/index.js
  src/Components/Shared/Row/index.jsx
  src/Components/Shared/Row/row.module.css
  src/Routes/auth.js
Labels: Ready for Deploy

#63 BaSP-TG-133: Add Edit feature for Project Managers
  src/Components/Employees/Projects/index.jsx
  src/Components/Projects/index.jsx
  src/Components/Shared/Button/button.module.css
  src/Components/Shared/Row/index.jsx
  src/Components/Shared/Row/row.module.css
  src/Components/SuperAdmins/Form/index.jsx
  src/Routes/employee.js
Labels: Ready for QA
